language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build
- dotnet test DALTest/DALTest.csproj
-dotnet test BLLTest/BLLTest.csproj
branches:
  only:
  - master
  - development